### ISSUE TITLE
[Question] Kernel for gameservers - Debian?

### ISSUE THREAD

**Issue by mrc4tt** [ToeiRei/kernel-deb#17]
Hi,

The kernel for gameservers (e.g. bare metal dedicated server)

Is that only Gentoo as recommended? or do you have .deb files for Debian? ^

**Comment by ToeiRei** [comment]
The kernel patchsets are the ones from gentoo - packaged as debs

**Comment by mrc4tt** [comment]
Alrighty.

Which will you recommend for Debian, if I run some gameservers (as examples) ^
Should I take the BM version based on a dedicated server (e.g.)?

**Comment by ToeiRei** [comment]
If you are planning to use a VM for a gameserver, you may want to rethink the whole installation as you do not want to have LVM slowing you down and stuff. I would suggest you hit me up on discord for a more in-depth discussion.
